### ISSUE TITLE
Resolution?

### ISSUE THREAD

**Issue by m-selig** [Cleric-K/Universal-RC-Joystick#1]
Interesting.  Thanks for posting.  On the PC side of things, what is the resolution in counts?

**Comment by Cleric-K** [comment]
Hi Rex,

I didn't put much thought into the license. I wouldn't even consider it if it was not for GH to suggest picking a license. I changed it to MIT if you think that's more useful.

About the resolution, the code is here:

https://github.com/Cleric-K/Universal-RC-Joystick/blob/f21a11a196980a6d5e19f28d66ed0f89e98285a4/Src/protocol_common.c#L39-L45

So receiver data comes almost in all cases with resolution of 1000 points (range 1000 - 2000). I map that to 0 - 32767.

Some time ago I tried to raise the question of increasing the resolution in Betaflight HID https://github.com/betaflight/betaflight/issues/6791 but the devs were reluctant. So the range is -127 to 127 in BF.

Negative values are problematic in some sims such as fpvfreerider, fpv air. After testing numerous commercial joysticks I saw that the general practice is to use the 0 - 32767 range. These are 16-bit _signed_ integers but only the positive half (0x0 - 0x7FFF) is used. This gives plenty of resolution (in our case, far more than the original 1000 points) and avoids the signed values problems.

**Comment by m-selig** [comment]
The MIT license is more useful because your code can get used in more projects, it will get more eyeballs/involvement, and for instance, you can also use your code in many more ways and in fact develop it commercially while not releasing any great new features that you might not want to share ... if you go that direction.  The GNU GPL completely ties your hands, and most people are not using it on new projects these days.  I'm glad to see that you are capturing as much resolution as is available from the source input.  I don't know about Betaflight (BF), but -127 to 127 might be OK for flipping/flopping around dynamically all the time with a quadcopter and never trying to fly perfectly straight with precision, but for an airplane that is not enough to trim and fly an aerobatic airplane straight (in any direction).  To trim an airplane can take, say, 0.1 deg of elevator deflection (i.e. pilots will notice an airplane being out of trimmed/straight flight with a 0.1 deg flick of the elevator trim or stick).  Now, consider an aerobatic 3D airplane with max elevator deflections of +/- 50 deg.  To get that resolved to 0.1 deg takes 1000 clicks.  So a minimum good resolution would be -500 to +500, or 0 to +1000.  So +/-127 is only 256 clicks -- that is only 1/4 resolution needed for this example (a very real example in a popular category).  Now if for a *different* airplane, the elevator only travels +/-12.5 deg, then 256 clicks is enough.  But most any interesting RC airplane (non-trainer) will have more elevator deflection than +/-12.5 deg.  So point is: I think you're on the right track w/ not limiting it in your code.

**Comment by m-selig** [comment]
Yes, going w/ only positive values makes the most sense and is easiest to handle.  If one were to go w/ +/- values on the limits, then it presupposed that something around 0 is center.  But some sticks don't center.  BTW  8 proportional channels would be more useful.  Even putting Tx switches on a proportional channel is easier to deal w/ on the simulator side of code.

**Comment by Cleric-K** [comment]
Hi Rex,
I sought a balance between axes and buttons because I wanted to keep the tool with zero-configuration. Initially I thought about the ability to configure the mappings but this would have meant that additional software would be needed. This software would have to be compatible with all the OSes and so on. That's why I decided to strike a balance and keep everything working without any additional software. This makes it possible to use the device with any platform/OS (Android, Mac, etc.)

I don't know if you're aware of my other project https://github.com/Cleric-K/vJoySerialFeeder
It allows you to make completely custom mappings between channels and axes/buttons. But it is Windows/Linux only. Part of the motivation for the project here was that people asked about MacOS. I tried to port but it turned out there's no suitable virtual joystick driver of MacOS. That's why a hardware solution was more appropriate, which would run right out of the box.

vJoySerialFeeder doesn't use USB emulation but directly reads the UART signal of the receiver (you need USB UART converted such as FTDI or Arduino). Then you can do quite a lot with the raw channel data. You can map it to axes, buttons, you can script in Lua.

**Comment by m-selig** [comment]
I am tempted to try this out.
I did not notice your other project before (vJoySerialFeeder).  Can that other program be used to *remap* an existing joystick controller to another virtual controller (if I'm using the terminology correctly).  I am asking about Windows application here.  I only care about Windows for simulations.  The RC simulator software that I use only runs on Windows and will only ever run on Windows.

**Comment by Cleric-K** [comment]
No, vJoySerialFeeder works only with serial port protocols. But you have several options for joystick remapping. 

http://whitemagic.github.io/JoystickGremlin/ is one possibility and also on the page there's a list with other similar tools.

**Comment by m-selig** [comment]
Thank you.  That is new to me.
